Document: sendsms
Title: Debian sendsms Manual
Author: <insert document author here>
Abstract: This manual describes what sendsms is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sendsms/sendsms.sgml.gz

Format: postscript
Files: /usr/share/doc/sendsms/sendsms.ps.gz

Format: text
Files: /usr/share/doc/sendsms/sendsms.text.gz

Format: HTML
Index: /usr/share/doc/sendsms/html/index.html
Files: /usr/share/doc/sendsms/html/*.html
